version: '3.8'
services:
  backend:
    build:
      context: ./backend/todolist
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - banco
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/todo_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:14
    container_name: todo_db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=todo_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - banco
volumes:
  pgdata:
networks:
  banco:
    driver: bridge
